# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
