# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_myproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProducts',
            new_name='MyProduct',
        ),
    ]
