# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20160526_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProduct',
            new_name='MyProducts',
        ),
        migrations.AlterModelOptions(
            name='myproducts',
            options={'verbose_name': 'My Products', 'verbose_name_plural': 'My Products'},
        ),
    ]
