# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 21:38
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='media',
            field=models.ImageField(blank=True, height_field='height', null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/rommelrico/Documents/github/play/python/DigitalMarketplace/static_cdn/protected'), upload_to=products.models.download_media_location, width_field='width'),
        ),
    ]
