# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_remove_thumbnail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
