# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20160526_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_active',
            field=models.BooleanField(default=False),
        ),
    ]
